cc_library(
  name = "hello-time",
  srcs = ["hello-time.cc"],
  hdrs = ["hello-time.h"],
  visibility = [
    "//main:__pkg__",
    "//test:__pkg__",
  ],
)

cc_library(
  name = "hello-greet",
  srcs = ["hello-greet.cc"],
  hdrs = ["hello-greet.h"],
  visibility = [
    "//main:__pkg__",
    "//test:__pkg__",
  ],
)
